-- 수동 운동 완료 기록과 요일별 루틴 스케줄 지원을 위한 스키마 업데이트

-- 1) routine_record 테이블 확장: 자세 도우미 외 수동 기록 지원
ALTER TABLE public.routine_record
  ADD COLUMN IF NOT EXISTS completion_method text DEFAULT 'pose_assisted';

ALTER TABLE public.routine_record
  ADD COLUMN IF NOT EXISTS manual_notes text;

ALTER TABLE public.routine_record
  ADD COLUMN IF NOT EXISTS perceived_intensity smallint CHECK (perceived_intensity BETWEEN 1 AND 10);

ALTER TABLE public.routine_record
  ADD COLUMN IF NOT EXISTS is_user_reported boolean DEFAULT false;

ALTER TABLE public.routine_record
  ADD COLUMN IF NOT EXISTS session_status text DEFAULT 'completed';

COMMENT ON COLUMN public.routine_record.completion_method IS 'pose_assisted | manual 등 세션 완료 방식';
COMMENT ON COLUMN public.routine_record.manual_notes IS '사용자 수동 입력 메모';
COMMENT ON COLUMN public.routine_record.perceived_intensity IS '사용자가 기록한 RPE (1~10)';
COMMENT ON COLUMN public.routine_record.is_user_reported IS '사용자가 직접 기록한 세션 여부';
COMMENT ON COLUMN public.routine_record.session_status IS 'completed, in_progress 등 세션 상태';

-- 2) 요일별 루틴 스케줄 테이블 생성
CREATE TABLE IF NOT EXISTS public.routine_schedule (
  schedule_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  routine_id integer NOT NULL REFERENCES public.routine(routine_id) ON DELETE CASCADE,
  weekday smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6), -- 0=월, 6=일
  start_time time without time zone,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  note text,
  created_at timestamp without time zone DEFAULT now()
);

-- 중복 방지를 위한 유니크 인덱스
CREATE UNIQUE INDEX IF NOT EXISTS routine_schedule_user_weekday_idx
  ON public.routine_schedule (user_id, weekday, routine_id, sort_order);
